### ISSUE TITLE
docs: search for particular section

### ISSUE THREAD

**Issue by mgenov** [clouway/docs.clouway.com#26]
The users should be able to search for a particular document or page using the UI. Gatsby provides a plugin for these features:

https://www.gatsbyjs.org/docs/adding-search/

In our case, professional services for search are not required and for this reason libraries like elasticlunr or js-search could be checked.

**Comment by mgenov** [comment]
Maybe this plugin: https://github.com/gatsby-contrib/gatsby-plugin-elasticlunr-search is the easiest and best option for us.

**Comment by mgenov** [comment]
A Plugin with multilingual support: https://github.com/humanseelabs/gatsby-plugin-lunr

**Comment by mgenov** [comment]
Here is a nice search component used in the page header which could be considered an option:

![Search](https://user-images.githubusercontent.com/209223/61700687-983d1780-ad45-11e9-930c-5d1d0e14832a.gif)


Endpoint: https://cloud.google.com/s/results/?q=app+engine&p=%2F

**Comment by GrishaAngelov** [comment]
I tried to experiment with the given plugins and it turns out that: 
- for ```gatsby-contrib/gatsby-plugin-elasticlunr-search``` it seems that works only in english without option to register any other language. As far as I am able to understand it uses ```stemmer``` function which is adapted for english words and can't be overrided ( even if we have bg stemmer function )

- for ```gatsby-plugin-lunr``` it support several languages but bulgarian is not one of them.
https://lunrjs.com/guides/language_support.html
![image](https://user-images.githubusercontent.com/1625243/61867495-061d4680-aee0-11e9-80c2-00e91c8c2e39.png)

It looks  possible to register own "language" i.e. stemmer but it seems that it would be implemented from scratch

sample for DE: https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.de.js

**Comment by mgenov** [comment]
We can add a simple "stemmer" that we used on the backend. I know that it's not a real one but provides a good search capabilities.

**Comment by GrishaAngelov** [comment]
Actually it seems that  ```gatsby-plugin-lunr``` like the other plugin can't add new language if it is not implemented in ```lunr-languages```....

![Screenshot from 2019-07-30 10-39-52](https://user-images.githubusercontent.com/1625243/62111143-9f6da380-b2b8-11e9-872d-9e68efd393d6.png)

The implementation of the plugin load languages from  ```lunr-languages```
https://github.com/humanseelabs/gatsby-plugin-lunr/blob/master/src/common.js
